### ISSUE TITLE
ERROR: Missing binary

### ISSUE THREAD

**Issue by OreCB** [conan-io/docs#3470] opened 2023-11-23 19:57 UTC
Hello,

I started having the issue two days ago, on November 21, 2023.
This is the same procedure I have used for the past year. There was no change in the source code or conanfile.
I am using Azure DevOps windows-2022
Conan version: 2.0.0
Conan Artifactory: 7.55.14 rev 75514900
The default Profile is:
![image](https://github.com/conan-io/docs/assets/100802977/6c479e6a-dd47-4605-a1a4-70a1afda4e04)

**First step:** I create a Conan package. Let's call it package A.
**Second step:** I upload that package to my local Conan server.
**Third Step:** I do a Conan Install for a different conanfile that consumes the package A.
I get an error saying there is no binary for that configuration.
ERROR: Missing binary: packageA:**d504f64a12c9ad3b96978d23328bd3a8afed1ed9**
This is the complete package revision and binary that is missing:
packageA#c61647ec99757b3436a07d2b9ca6d100c6c45555:**d504f64a12c9ad3b96978d23328bd3a8afed1ed9**
![image](https://github.com/conan-io/docs/assets/100802977/5fa30017-5dd9-48d8-9ab5-a8b1bee1a045)

If I check my Conan server for that package A, I just uploaded. The binary is there:
The problem is that the package was uploaded for a different binary hash:
packageA#c61647ec99757b3436a07d2b9ca6d100c6c45555:**517aa2a905662700f018a86f3a0dc9e3d8fc2a56**
If I check the conaninfo for that binary, it is the same configuration:
![image](https://github.com/conan-io/docs/assets/100802977/ad9281ac-a996-46ea-b392-e36409f1fe4c)

As I said before, it was working 2 days ago, and I have not changed anything.
I'm not sure if something changed in the way the binary hash is calculated when building the package and when consuming the package. Becuase, if I build the package A and consume it locally in a different package all works fine.
Something like this:

**First step:** I create a Conan package. Let's call it package A.
**Second Step:** I do nothing here. I will be consuming the package from the local cache.
**Third Step:** I do a Conan Install for a different conanfile that consumes the package A.
It all works fine.

Of course, I'm simplifying this process. I don't want to build the package locally all time, plus there is no space in the Azure Hosted Agent, as these two packages are big.

Help, please.
Thanks.

**Comment by memsharded** [comment] 2023-11-23 20:16
Hi @OreCB 

Thanks for your question.
I might be missing some details: 
- Where are the dependencies fetched from? 
- Do you have your own local copy of those dependencies in your Artifactory too?
- What kind of consumer you have? what ``package_type``?

I'd say that the problem is that the ``nlohmann_json`` dependency has changed, you can check the different recipe revision. If there is a new dependency and the ``package_type`` relationship, it requires to build a new binary.

**Comment by OreCB** [comment] 2023-11-23 21:43
Hi,

I think I found the issue.
The package A, uses nlohmann_json and had the revision fixed to the 2a1d289af3674cfe01cf2c8eaf464c68 
![image](https://github.com/conan-io/docs/assets/100802977/8f587996-7c61-449d-a54b-e2df289020a1)

But the package B, I'm building also depends on nlohmann_json, but it didn't have the revision fixed, so it looks like nlohmann_json released a new revision for version 3.7.3. or for some reason it is defaulting to a different one, because Conan Center says that this is the lastest one:
![image](https://github.com/conan-io/docs/assets/100802977/85456709-48ce-4fb4-995d-f27bbccfd194)
but the packageB, that does not have a revision fixed, defaults to this one: 
![image](https://github.com/conan-io/docs/assets/100802977/978cb390-5bb1-459c-9fff-9988e7e9c9f6)
 (By the way, how can I see all the different revisions for a package in the new conancenter?)
That was the change in the conaninfo that generated the different package_id hash:
![image](https://github.com/conan-io/docs/assets/100802977/2e15ac7d-6a29-44fc-8834-0652ec446948)

Thank you for your help.
You can close it. 
I hope this helps other.

If you got to this point, remember to always control up to the revision level, especially for third party dependencies.
https://docs.conan.io/2/reference/binary_model/package_id.html

**Comment by memsharded** [comment] 2023-11-23 22:18
> (By the way, how can I see all the different revisions for a package in the new conancenter?)

You can use ``conan list pkg/version#* -r=conancenter`` to list revisions from the client

> If you got to this point, remember to always control up to the revision level, especially for third party dependencies.

Good point. We recently wrote this: https://docs.conan.io/2/devops/using_conancenter.html
For the cases when it is necessary to get full reproducibility the recommendations are using lockfiles, but also in many cases, having a copy of the packages in a private server could be recommended.


> Conan version: 2.0.0

As a side note, 2.0.14 contains literally hundreds of bug fixes and stabilization changes. By the stability commitment and our releases versioning, only latest patch of every minor version is recommended.


Closing the ticket, thanks for the feedback!

**Closed by memsharded** 2023-11-23 22:18 UTC
