### ISSUE TITLE
[question] Documentation of conanfile.py method test()

### ISSUE THREAD

**Issue by GiugAles** [conan-io/docs#1539] opened 2020-01-30 17:12 UTC
Hi everyone,

I was wondering where the conanfile.py method test() is documented, since I can't find it in the reference of the conanfile.py (https://docs.conan.io/en/latest/reference/conanfile/methods.html)

To be clear, I am not asking about the conan command conan test (https://docs.conan.io/en/latest/reference/commands/creator/test.html) but the method in the conanfile.py it references to. Is this method simply to have an access point for the command line or does it support other features as well?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2020-01-30 22:47
Moved this issue to the docs repo.

**Comment by danimtb** [comment] 2020-01-31 09:50
Duplicate of #865

**Closed by danimtb** 2020-01-31 09:50 UTC
