### ISSUE TITLE
Getting started CONAN_COMPILER in cmake

### ISSUE THREAD

**Issue by danimtb** [conan-io/docs#38] opened 2016-02-09 12:06 UTC
When doing getting started in Linux, following steps until:

```
$ cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
```

Reports:

```
WARN: CONAN_COMPILER variable not set, please make sure yourself that your compiler and version matches your declared settings
WARN: CONAN_COMPILER_VERSION variable not set, please make sure yourself that your compiler version matches your declared settings
```

I've solved that writing this in _CMakeLists.txt_:

```
set(CONAN_COMPILER "cmake") 
set(CONAN_COMPILER_VERSION "2.8")
```

Is this the way to proceed? Should that be included in getting started _CMakeLists.txt_ example?

**Comment by memsharded** [comment] 2016-02-09 12:29
No, leave it as-is. It is just telling to be careful with your declared settings. E.g.
If you used
```
$ conan install -s compiler="gcc" -s compiler.version=4.8
```

It is possible that your current gcc compiler selected by "Unix Makefiles" cmake generator is not 4.8, but another one you might have in the system. When using the ``conan build`` command, these values are defined to cmake, and checks can be done. When using ``cmake`` directly, there is no easy way to do so, so the message is just telling to be careful and ensure that the version used by cmake matches the version you have declared in conan. But no need to modify the files.

In any case, it seems we have to do something with these compiler checks, they are troublesome.

**Comment by danimtb** [comment] 2016-02-09 15:49
The thing is, after following steps, when I run:

    cmake --build .

It builds nothing, so getting started docs dont work at least in linux

**Comment by memsharded** [comment] 2016-02-09 16:19
Yes, there is a bug in 0.7.1. We are fixing it right now. If you installed with pip, you might try running "pip install conan==0.7"

**Comment by memsharded** [comment] 2016-02-09 18:39
We have just released 0.7.2, it should fix these problems, could you try it please?

**Comment by monsdar** [comment] 2016-02-09 18:53
Seems to be fixed on Windows at least.

I was able to freshly install Conan and build the examples (at least I did not get the Warnings described above). I'm using CMake and VS12 in a project that uses Protobuf.

**Comment by memsharded** [comment] 2016-02-09 22:29
Thanks Nils for reporting. Yep, in windows, for regular packages (compiled, not header-only), it seems to work. The problem is with header only libs, I have just submitted a new PR: https://github.com/conan-io/conan/pull/151

Hopefully this is the good one. Also, as a workaround if compiler checks cause trouble, the flag CONAN_DISABLE_CHECK_COMPILER should be useful (call from cmake as -DCONAN_DISABLE_CHECK_COMPILER=On). But I hope that you don't need this, and also that the submitted PR ends this nightmare of bugs around this cmake compiler checks. 
Thanks!

**Closed** 2017-03-21 16:04 UTC
